# Generated by Django 5.1.6 on 2025-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=16, unique=True)),
                ("owner_name", models.CharField(max_length=100)),
                ("expiration_date", models.DateField()),
                ("cvv", models.CharField(max_length=3)),
            ],
        ),
    ]
