# Generated by Django 5.1.6 on 2025-03-26 14:29

from django.db import migrations, models

import creditcards.models


class Migration(migrations.Migration):

    dependencies = [
        ("creditcards", "0002_alter_creditcard_expiration_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="id",
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="expiration_date",
            field=models.CharField(
                help_text="format: MM/YY",
                max_length=5,
                validators=[creditcards.models.validate_expiration_date],
                verbose_name="expiration date",
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="number",
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
