# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
default_stages: [pre-commit]

repos:
  # Black: formateador de Python
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      args: [--fast, --line-length=120]
      types: [python]
      files: "backend_main/|backend_bank/"

   # Ruff: linter y autofix para Python
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.9"
    hooks:
      - id: ruff
        args: ["--fix"]
        types: [python]
        files: "backend_main/|backend_bank/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.21.0
    hooks:
      - id: eslint
        args: ["--fix"]
        files: "frontend"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write", "*.ts", "*.json", "*.html", "*.scss"]
        files: "frontend"
