[lint]
select = ["F", "E", "W", "I001"]
task-tags = ["TODO", "FIXME"]
fixable = ["ALL"]
extend-ignore = ["E501", "E722"]

[lint.isort]
known-first-party = []
known-third-party = []
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]
combine-as-imports = true
split-on-trailing-comma = false
lines-between-types = 1
