# Generated by Django 5.1.6 on 2025-03-14 11:51

from decimal import Decimal

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register", "0006_user_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="account",
                        serialize=False,
                        to="register.user",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
