# Generated by Django 5.1.6 on 2025-03-18 01:23

from decimal import Decimal

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="account",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
