# Generated by Django 5.1.6 on 2025-04-20 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(condition=models.Q(("balance__gte", 0)), name="balance_non_negative"),
        ),
    ]
