# Generated by Django 5.1.6 on 2025-03-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
    ]
