# Generated by Django 5.1.6 on 2025-03-17 16:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_table"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="account",
                serialize=False,
                to="users.user",
            ),
        ),
    ]
