# Generated by Django 5.1.6 on 2025-03-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moneyrequest",
            old_name="requester",
            new_name="request_from",
        ),
        migrations.RenameField(
            model_name="moneyrequest",
            old_name="requested_from",
            new_name="request_to",
        ),
    ]
