# Generated by Django 5.1.6 on 2025-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="MoneyRequest",
        ),
    ]
