# Generated by Django 5.1.6 on 2025-03-17 16:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_requester_moneyrequest_request_from_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneyrequest",
            name="request_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="money_requests_sent", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="moneyrequest",
            name="request_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="money_requests_received", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions_received", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions_sent", to="users.user"
            ),
        ),
    ]
