# Generated by Django 5.1.6 on 2025-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_status_delete_moneyrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"get_latest_by": "created_at", "ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
