# Generated by Django 5.1.6 on 2025-04-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
    ]
