# Generated by Django 5.1.6 on 2025-04-02 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(choices=[("send", "Send"), ("receive", "Receive")], default="send", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("sender", models.F("receiver")), _negated=True), name="sender_receiver_different"
            ),
        ),
    ]
