# Generated by Django 5.1.6 on 2025-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(choices=[("send", "Send"), ("receive", "Receive")], max_length=10),
        ),
    ]
