# Generated by Django 5.1.6 on 2025-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_transaction_transaction_status_505a2f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(choices=[("send", "Send"), ("request", "Request")], default="send", max_length=10),
        ),
    ]
