# Generated by Django 5.1.6 on 2025-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("id_number", models.CharField(max_length=20, unique=True)),
                ("rol", models.IntegerField(default=0)),
                ("password", models.CharField(blank=True, default="", max_length=128, null=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
