# Generated by Django 5.1.6 on 2025-03-17 16:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendships", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="received_requests", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sent_requests", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="friendship_user1", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="friendship_user2", to="users.user"
            ),
        ),
    ]
