# Generated by Django 5.1.6 on 2025-03-17 18:18

import django.db.models.deletion
import encrypted_model_fields.fields

from django.db import migrations, models

import creditcard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "number",
                    encrypted_model_fields.fields.EncryptedCharField(primary_key=True, serialize=False, unique=True),
                ),
                ("owner_name", models.CharField(max_length=100, verbose_name="owner name")),
                (
                    "expiration_date",
                    models.CharField(
                        help_text="format: MM/YY",
                        max_length=5,
                        validators=[creditcard.models.validate_expiration_date],
                        verbose_name="expiration date",
                    ),
                ),
                ("cvv", encrypted_model_fields.fields.EncryptedCharField()),
                ("card_alias", models.CharField(blank=True, max_length=100, null=True, verbose_name="alias")),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credit_cards", to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "credit_cards",
                "constraints": [models.UniqueConstraint(fields=("user", "is_default"), name="unique_default_card")],
            },
        ),
    ]
