# Generated by Django 5.1.6 on 2025-03-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
        ('register', '0006_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name on card'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='register.user'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.UniqueConstraint(fields=('user', 'is_default'), name='unique_default_card'),
        ),
        migrations.AlterModelTable(
            name='creditcard',
            table='credit_cards',
        ),
    ]
