# Generated by Django 5.1.6 on 2025-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditcard", "0002_creditcard_is_default_creditcard_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="name",
        ),
        migrations.AddField(
            model_name="creditcard",
            name="card_alias",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="alias"),
        ),
    ]
