# Generated by Django 5.1.7 on 2025-03-29 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditcard", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="creditcard",
            name="unique_default_card",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="cvv",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="is_default",
        ),
        migrations.AddConstraint(
            model_name="creditcard",
            constraint=models.UniqueConstraint(fields=("user",), name="unique_default_card"),
        ),
    ]
