# Generated by Django 5.1.7 on 2025-03-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0003_remove_creditcard_unique_default_card_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditcard',
            name='unique_default_card',
        ),
    ]
