# Generated by Django 5.1.6 on 2025-03-15 12:01

from django.db import migrations, models

import creditcard.models


class Migration(migrations.Migration):

    dependencies = [
        ("creditcard", "0003_remove_creditcard_name_creditcard_card_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="expiration_date",
            field=models.CharField(
                help_text="format: MM/YY",
                max_length=5,
                validators=[creditcard.models.validate_expiration_date],
                verbose_name="expiration date",
            ),
        ),
    ]
