# Generated by Django 5.1.6 on 2025-03-17 16:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditcard", "0004_alter_creditcard_expiration_date"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="credit_cards", to="users.user"
            ),
        ),
    ]
