# Generated by Django 5.1.6 on 2025-03-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditcard", "0004_remove_creditcard_unique_default_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="number",
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
