# Generated by Django 5.1.6 on 2025-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rol",
            field=models.IntegerField(default=0),
        ),
    ]
