# Generated by Django 5.1.6 on 2025-03-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_card_number',
        ),
    ]
