# Generated by Django 5.1.6 on 2025-03-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_remove_user_credit_card_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
