# Generated by Django 5.1.7 on 2025-03-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
